apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sde-application-staging
  namespace: argocd

  labels:
    app.kubernetes.io/name: sde
    app.kubernetes.io/component: staging
    app.kubernetes.io/managed-by: github-actions

  annotations:
    environment.sde/type: staging

spec:
  project: simple-data-exchanger

  source:
    repoURL: https://github.com/ARENA2036/managed-simple-data-exchanger.git
    targetRevision: develop
    path: charts/simpledataexchanger

    helm:
      releaseName: sde

      valueFiles:
        - values-staging.yaml

      parameters:
        - name: backend.image.tag
          value: REPLACE_BACKEND_TAG
          forceString: true

        - name: frontend.image.tag
          value: REPLACE_FRONTEND_TAG
          forceString: true

  destination:
    name: arenax-ap6
    namespace: simple-data-exchanger

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

  revisionHistoryLimit: 3