apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: simple-data-exchanger
  namespace: argocd

  labels:
    app.kubernetes.io/name: sde
    app.kubernetes.io/component: developer-preview
    app.kubernetes.io/managed-by: github-actions

  annotations:
    preview.sde/branch: REPLACE_BRANCH_NAME

spec:
  project: simple-data-exchanger

  source:
    repoURL: https://github.com/ARENA2036/managed-simple-data-exchanger.git
    targetRevision: REPLACE_BRANCH_NAME
    path: charts/simpledataexchanger

    helm:
      releaseName: REPLACE_RELEASE_NAME

      valueFiles:
        - values-dev.yaml

      parameters:
        - name: backend.image.tag
          value: REPLACE_BACKEND_TAG
          forceString: true

        - name: frontend.image.tag
          value: REPLACE_FRONTEND_TAG
          forceString: true

  destination:
    name: arenax-ap6
    namespace: REPLACE_NAMESPACE

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

  revisionHistoryLimit: 3