name: Create Harbor Registry Secret

on:
  workflow_dispatch:
    inputs:
      deployment_type:
        description: "Target environment"
        required: true
        type: choice
        options:
          - int-ap6-preview
          - int-ap6-shared-dev
          - staging
          - production

      namespace:
        description: "Target namespace"
        required: false
        type: string

jobs:
  create-registry-secret:
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

      HBR_USERNAME: ${{ secrets.HBR_USERNAME }}
      HBR_PASSWORD: ${{ secrets.HBR_PASSWORD }}

      DEPLOYMENT_TYPE: ${{ github.event.inputs.deployment_type }}
      TARGET_NAMESPACE: ${{ github.event.inputs.namespace }}

    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)

          curl -LO \
            https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl

          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Vault
        run: |
          VAULT_VERSION=1.18.3

          curl -LO \
            https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip

          unzip vault_${VAULT_VERSION}_linux_amd64.zip

          chmod +x vault
          sudo mv vault /usr/local/bin/

      - name: Load kubeconfig from Vault
        run: |

          case "${DEPLOYMENT_TYPE}" in
            int-ap6-preview|int-ap6-shared-dev)
              VAULT_SECRET_PATH="staging/infra/cluster-int"
              ;;
            staging)
              VAULT_SECRET_PATH="staging/infra/cluster-staging"
              ;;
            production)
              VAULT_SECRET_PATH="staging/infra/cluster-prod"
              ;;
            *)
              echo "Unknown deployment type"
              exit 1
              ;;
          esac

          mkdir -p ~/.kube

          vault kv get \
            -field=config \
            ${VAULT_SECRET_PATH} > ~/.kube/config

          chmod 600 ~/.kube/config

          kubectl config current-context

      - name: Create Harbor Registry Secret
        run: |

          kubectl create namespace ${TARGET_NAMESPACE} \
            --dry-run=client \
            -o yaml | kubectl apply -f -

          kubectl create secret docker-registry registry-creds \
            --docker-server=harbor-hub-shared.arena.3ascloud.de \
            --docker-username="${HBR_USERNAME}" \
            --docker-password="${HBR_PASSWORD}" \
            --namespace=${TARGET_NAMESPACE} \
            --dry-run=client \
            -o yaml | kubectl apply -f -

          kubectl get secret registry-creds \
            -n ${TARGET_NAMESPACE}